export const securityEventTypes = [
  'LoginSucceeded',
  'LoginFailed',
  'Logout',
  'TokenValidationFailed',
  'TokenExpired',
  'TenantResolved',
  'TenantAccessDenied',
  'Forbidden',
  'Unauthorized',
  'RateLimitExceeded',
  'ReportExported',
  'ReportViewed',
  'ClientListed',
  'ClientViewed',
  'ClientDetailViewed',
  'EnrollmentListed',
  'InteractionListed',
  'FollowUpsListed',
  'DataImported',
  'ClientDeleted',
  'EnrollmentDeleted',
  'InteractionDeleted',
  'OrganizationUserChanged',
  'TenantChanged',
] as const

const eventTypeLabels: Record<string, string> = {
  LoginSucceeded: 'Login succeeded',
  LoginFailed: 'Login failed',
  Logout: 'Logout',
  TokenValidationFailed: 'Token validation failed',
  TokenExpired: 'Token expired',
  TenantResolved: 'Tenant resolved',
  TenantAccessDenied: 'Tenant access denied',
  Forbidden: 'Forbidden',
  Unauthorized: 'Unauthorized',
  RateLimitExceeded: 'Rate limit exceeded',
  ReportExported: 'Report exported',
  ReportViewed: 'Report viewed',
  ClientListed: 'Client list viewed',
  ClientViewed: 'Client viewed',
  ClientDetailViewed: 'Client detail viewed',
  EnrollmentListed: 'Enrollments viewed',
  InteractionListed: 'Interactions viewed',
  FollowUpsListed: 'Follow-ups viewed',
  DataImported: 'Data imported',
  ClientDeleted: 'Client deleted',
  EnrollmentDeleted: 'Enrollment deleted',
  InteractionDeleted: 'Interaction deleted',
  OrganizationUserChanged: 'User access changed',
  TenantChanged: 'Organization access changed',
}

export function formatSecurityEventType(eventType: string) {
  return eventTypeLabels[eventType] ?? eventType.replace(/([a-z])([A-Z])/g, '$1 $2')
}
